import { Sailboat, House, Plane, Car, Wand2, Video, FileText } from "lucide-react";
import type { IndustryConfig, IndustryId } from "./types";
import yachtImg from "@/assets/hero-yacht.jpg";
import villaImg from "@/assets/eco-villa.jpg";
import jetImg from "@/assets/eco-jet.jpg";
import carImg from "@/assets/eco-car.jpg";

const studioActions = [
  { label: "Generate from market signal", desc: "Auto-draft from today's intelligence" },
  { label: "AI cinematic reel", desc: "Upload clips → finished luxury edit" },
  { label: "Authority essay", desc: "Long-form for LinkedIn / Substack" },
];
export const studioActionIcons = [Wand2, Video, FileText];

export const INDUSTRIES: Record<IndustryId, IndustryConfig> = {
  yachts: {
    id: "yachts",
    label: "Yachts",
    shortLabel: "Yacht",
    modeLabel: "Yacht Mode",
    icon: Sailboat,
    tagline: "Brokerage · Charter · Monaco",
    ambientImage: yachtImg,
    mentorPersona: "AURUM · Yachting Counsel",
    mentorSpecialty: "Brokerage, charter, owner psychology · Monaco-rooted",
    mentorOpener:
      "Good morning, Alexander. I reviewed last night's brokerage activity and your follow-up queue. Before we plan today: how did the call with the Camper & Nicholsons broker land?",
    mentorPrompts: [
      "Plan my Monaco Yacht Show week",
      "Review my brokerage LinkedIn positioning",
      "Draft a charter inquiry to a UHNW prospect",
      "Coach me through a senior broker conversation",
    ],
    greetingSubtitle: "The Mediterranean charter market is moving — and so are you.",
    phaseLabel: "Phase 02 · Brokerage immersion",
    dailyObjectives: [
      "Message 5 yacht brokers in Monaco",
      "Publish a market insight on Med charter season",
      "Follow up with 2 prospects from Cannes",
      "Academy: Luxury sales psychology — Module 04",
      "Engage with 6 yachting industry posts",
    ],
    marketTrends: ["Hybrid superyachts +240%", "Med charter -18% YoY", "Refit yards booked into Q3"],
    upcoming: [
      ["Sept 24", "Monaco Yacht Show — VIP preview"],
      ["Oct 02", "Mastermind: Charter Season Q4"],
      ["Oct 11", "1:1 with Marco D. (Edmiston)"],
    ],
    aiRecommendation:
      "Reach out to Edmiston's Monaco office before the show — your authority profile fits their charter pipeline.",
    intelFeed: [
      { tag: "MARKET", title: "Benetti Oasis 67m delivered — Med charter inventory tightens 18% YoY", note: "Reposition early. Brokers with summer 2026 capacity unbooked should secure UHNW commitments now.", time: "12m", region: "Monaco" },
      { tag: "DEAL", title: "Feadship 84m 'Lonian' sold off-market — Burgess closed", note: "Confirms appetite at $200M+ segment despite rate environment. Watch successor inquiries.", time: "44m", region: "Amsterdam" },
      { tag: "PEOPLE", title: "Bernard Arnault yacht 'Symphony' refit at Lürssen — 8 weeks", note: "Spring relaunch likely. Vendor pipeline opens (interior, AV, chef).", time: "2h", region: "Bremen" },
      { tag: "EVENT", title: "Cannes Yachting Festival dates confirmed — Sept 8–13", note: "12 high-tier prospects in your network attending. Pre-show outreach window: 6 weeks.", time: "5h", region: "Cannes" },
      { tag: "CULTURE", title: "Hybrid superyachts: search volume up 240% on luxury portals", note: "Authority opportunity. Publish primer this week before competitor brokerages.", time: "8h", region: "Global" },
      { tag: "REGULATORY", title: "Italian VAT lease scheme tightened for charter operators", note: "Affects ~60% of Med-flagged charter inventory. Talking point with Italian UHNW.", time: "1d", region: "Rome" },
    ],
    circles: [
      { name: "Monaco Brokerage Mastermind", members: 24, tier: "TIER-1", note: "Senior brokers · invitation-only" },
      { name: "Charter Operators Circle", members: 41, tier: "TIER-2", note: "Captains, charter managers, owners' reps" },
      { name: "Authority Builders", members: 118, tier: "OPEN", note: "Content, personal brand, positioning" },
      { name: "Med vs Caribbean Q4", members: 67, tier: "SEASONAL", note: "Active discussion · 12 today" },
    ],
    people: [
      { n: "Marco Donatelli", r: "Senior Broker · Edmiston", c: "Monaco", tier: "1" },
      { n: "Sophia Renier", r: "Charter Director · Burgess", c: "London", tier: "1" },
      { n: "Henrik Lange", r: "Refit Specialist · Lürssen", c: "Bremen", tier: "2" },
      { n: "Layla Haddad", r: "UHNW Family Office", c: "Dubai", tier: "1" },
      { n: "Olivier Tassan", r: "Captain · 80m Feadship", c: "Antibes", tier: "2" },
      { n: "Anaïs Marchetti", r: "Marina Director · Port Hercule", c: "Monaco", tier: "2" },
    ],
    introContext: "Mutual context: 3 active charter mandates in the Med.",
    contentPrompts: [
      { type: "LinkedIn", t: "Why hybrid superyachts will define the next decade" },
      { type: "Reel", t: "60s tour: inside a €38M Benetti" },
      { type: "Carousel", t: "5 things a senior broker notices that you don't" },
      { type: "Short", t: "Why this 73m's resale just signalled a soft secondary" },
    ],
    studioActions,
    trackName: "Yacht Brokerage",
    trackModules: 42,
    trackProgress: 28,
    modules: [
      { n: "01", t: "The architecture of trust with UHNW owners", dur: "14 min", state: "done" },
      { n: "02", t: "Reading a yacht spec sheet like a senior broker", dur: "22 min", state: "done" },
      { n: "03", t: "Charter season dynamics — Med vs Caribbean", dur: "18 min", state: "done" },
      { n: "04", t: "Luxury sales psychology — restraint as leverage", dur: "26 min", state: "current" },
      { n: "05", t: "Building a buyer mandate from a single conversation", dur: "31 min", state: "locked" },
      { n: "06", t: "Owner representation: the unwritten code", dur: "24 min", state: "locked" },
    ],
    tutorBlurb:
      "Drill 'restraint as leverage' through a live role-play with AURUM — playing the part of a skeptical 80m-yacht owner.",
    terms: { client: "Owner", asset: "Yacht", market: "Charter market" },
  },

  villas: {
    id: "villas",
    label: "Villas",
    shortLabel: "Villa",
    modeLabel: "Villa Mode",
    icon: House,
    tagline: "Ultra-prime real estate · Dubai · Miami · Monaco",
    ambientImage: villaImg,
    mentorPersona: "AURUM · Ultra-Prime Counsel",
    mentorSpecialty: "Trophy real estate, UHNW investors, developers · Dubai/Miami/Monaco",
    mentorOpener:
      "Good morning, Alexander. Three new trophy listings hit the Dubai and Monaco markets overnight. Before we plan: did your introduction with the Knight Frank Private Office land?",
    mentorPrompts: [
      "Plan my Dubai trophy market week",
      "Review my luxury real estate positioning",
      "Draft outreach to a UHNW investor",
      "Coach me through a developer pitch",
    ],
    greetingSubtitle: "The ultra-prime market is moving — and so are you.",
    phaseLabel: "Phase 02 · Trophy listings immersion",
    dailyObjectives: [
      "Analyze 5 new ultra-prime listings",
      "Comment on 3 luxury architecture posts",
      "Publish a market insight on Dubai prime",
      "Academy: Reading a trophy property like an insider",
      "Outreach to 2 luxury developers",
    ],
    marketTrends: ["Dubai prime +29% YoY", "Miami waterfront supply -12%", "Monaco €/m² record"],
    upcoming: [
      ["Oct 06", "Dubai Luxury Property Show"],
      ["Oct 18", "Mastermind: Branded Residences"],
      ["Oct 27", "1:1 with Helena V. (Knight Frank)"],
    ],
    aiRecommendation:
      "Reach Knight Frank's Dubai Private Office before the Luxury Property Show — your buyer mandate aligns with their pipeline.",
    intelFeed: [
      { tag: "MARKET", title: "Dubai prime AED 70M+ transactions up 29% YoY", note: "Palm Jumeirah and Emirates Hills lead; supply at trophy tier remains constrained.", time: "18m", region: "Dubai" },
      { tag: "DEAL", title: "Bal Harbour penthouse closes at $48M — record psf for tower", note: "Buyer LATAM family office. Signals appetite for Miami trophy despite rates.", time: "1h", region: "Miami" },
      { tag: "PEOPLE", title: "Aman Residences NYC owner-list — discreet resale, $65M", note: "Branded residences resale gaining a real secondary market. Mandate opportunity.", time: "3h", region: "New York" },
      { tag: "EVENT", title: "Monaco Property Days — Nov 14–15 confirmed", note: "Private wealth managers + developer principals. RSVP windows close in 3 weeks.", time: "5h", region: "Monaco" },
      { tag: "CULTURE", title: "'Quiet luxury' interiors driving 2-week listing premiums on prime portals", note: "Stage / position prime listings around restraint — buyers are deciding faster.", time: "9h", region: "Global" },
      { tag: "REGULATORY", title: "Portugal Golden Visa final tightening — investors rotating to UAE", note: "UAE Golden Residency inflow to accelerate Q4. Pipeline opens with UAE legal partners.", time: "1d", region: "Lisbon" },
    ],
    circles: [
      { name: "Dubai Trophy Brokers", members: 31, tier: "TIER-1", note: "Palm, Emirates Hills, Bvlgari Residences" },
      { name: "Branded Residences Council", members: 52, tier: "TIER-2", note: "Aman, Bvlgari, Four Seasons, Rosewood reps" },
      { name: "Authority Builders", members: 118, tier: "OPEN", note: "Content, personal brand, positioning" },
      { name: "UHNW Buyer Mandates Q4", members: 44, tier: "SEASONAL", note: "Active mandates · 9 today" },
    ],
    people: [
      { n: "Helena Vargas", r: "Head · Knight Frank Private Office", c: "Dubai", tier: "1" },
      { n: "Lukas Stein", r: "Partner · Sotheby's International", c: "Miami", tier: "1" },
      { n: "Yara Al Hashimi", r: "Developer Principal", c: "Abu Dhabi", tier: "1" },
      { n: "Pierre Beaumont", r: "Monaco Real Estate", c: "Monaco", tier: "2" },
      { n: "Naomi Croft", r: "Branded Residences Director · Aman", c: "London", tier: "1" },
      { n: "Roberto Salvi", r: "Architect · Trophy Villas", c: "Como", tier: "2" },
    ],
    introContext: "Mutual context: 2 active UHNW buyer mandates above $40M.",
    contentPrompts: [
      { type: "LinkedIn", t: "Why branded residences are the new trophy asset" },
      { type: "Reel", t: "Walkthrough: a $48M Bal Harbour penthouse" },
      { type: "Carousel", t: "5 things a trophy buyer looks at before price" },
      { type: "Short", t: "Why Dubai's AED 70M+ tier just broke a record" },
    ],
    studioActions,
    trackName: "Ultra-Prime Real Estate",
    trackModules: 38,
    trackProgress: 14,
    modules: [
      { n: "01", t: "Reading a trophy listing like a private banker", dur: "16 min", state: "done" },
      { n: "02", t: "Branded residences: structure, premium, secondary market", dur: "24 min", state: "done" },
      { n: "03", t: "Sourcing pocket-listings in Dubai and Monaco", dur: "20 min", state: "current" },
      { n: "04", t: "Working with family offices vs single principals", dur: "28 min", state: "locked" },
      { n: "05", t: "The buyer mandate playbook above €30M", dur: "30 min", state: "locked" },
      { n: "06", t: "Developer relationships: from intro to allocation", dur: "26 min", state: "locked" },
    ],
    tutorBlurb:
      "Role-play sourcing a pocket-listing for an UHNW principal — AURUM plays the part of a discreet Monaco seller's broker.",
    terms: { client: "Principal", asset: "Residence", market: "Prime market" },
  },

  jets: {
    id: "jets",
    label: "Jets",
    shortLabel: "Jet",
    modeLabel: "Jet Mode",
    icon: Plane,
    tagline: "Private aviation · brokerage · charter · UHNW travel",
    ambientImage: jetImg,
    mentorPersona: "AURUM · Aviation Counsel",
    mentorSpecialty: "Aircraft brokerage, charter, fractional, UHNW travel",
    mentorOpener:
      "Good morning, Alexander. Pre-owned Globals and Falcons moved overnight. Before today's plan — how did the call with the VistaJet account director land?",
    mentorPrompts: [
      "Plan my EBACE / NBAA week",
      "Review my aviation LinkedIn positioning",
      "Draft outreach to a Global 7500 owner",
      "Coach me through a charter pricing call",
    ],
    greetingSubtitle: "Pre-owned long-range inventory is moving — and so are you.",
    phaseLabel: "Phase 02 · Aircraft brokerage immersion",
    dailyObjectives: [
      "Track 5 pre-owned Global / Falcon listings",
      "Comment on 3 aviation industry posts",
      "Publish a market insight on charter rate compression",
      "Academy: How a senior broker prices a Global 6000",
      "Outreach to 2 Part 135 operators",
    ],
    marketTrends: ["Global 7500 wait list +14 mo", "Charter rates -8% Q3", "Citation Latitude demand surging"],
    upcoming: [
      ["Oct 14", "NBAA-BACE Las Vegas"],
      ["Oct 24", "Mastermind: Fractional vs Whole-Aircraft"],
      ["Nov 02", "1:1 with Damien R. (Jetcraft)"],
    ],
    aiRecommendation:
      "Reach Jetcraft's pre-owned desk before NBAA — your buyer thesis fits their incoming Global inventory.",
    intelFeed: [
      { tag: "MARKET", title: "Global 7500 secondary market sees first sub-list-price closing in 14 months", note: "Discount of 4.2% off ask. Signals top-of-cycle softness for ultra-long-range.", time: "22m", region: "Geneva" },
      { tag: "DEAL", title: "Gulfstream G700 first owner-resale listed at Jetcraft — $79M ask", note: "Watch buyer profile — likely Middle East family office. Mandate opportunity.", time: "1h", region: "London" },
      { tag: "PEOPLE", title: "VistaJet adds 7 Global 7500 frames to fleet by Q1", note: "Fleet expansion creates broker pipeline for trade-in Globals and Falcons.", time: "2h", region: "Malta" },
      { tag: "EVENT", title: "NBAA-BACE Las Vegas confirmed Oct 14–16", note: "9 owners and 14 operators from your network attending. Strategic week.", time: "4h", region: "Las Vegas" },
      { tag: "CULTURE", title: "UHNW preference shifting back to whole-aircraft from jet cards", note: "Authority opportunity: publish on TCO of ownership vs program hours.", time: "8h", region: "Global" },
      { tag: "REGULATORY", title: "EASA tightens Part-NCC ops rules for private operators", note: "Affects ~30% of EU-registered owner-flown jets. Talking point with EU principals.", time: "1d", region: "Cologne" },
    ],
    circles: [
      { name: "Pre-Owned Brokers Council", members: 28, tier: "TIER-1", note: "Global, Falcon, G-series specialists" },
      { name: "Charter Operators Circle", members: 49, tier: "TIER-2", note: "Part 135 / EU-OPS principals" },
      { name: "Authority Builders", members: 118, tier: "OPEN", note: "Content, personal brand, positioning" },
      { name: "NBAA Pre-Show", members: 53, tier: "SEASONAL", note: "Active discussion · 18 today" },
    ],
    people: [
      { n: "Damien Rousseau", r: "Senior Broker · Jetcraft", c: "London", tier: "1" },
      { n: "Carla Mendoza", r: "VP Sales · VistaJet", c: "Malta", tier: "1" },
      { n: "Aaron Levy", r: "Founder · Levy Aviation Group", c: "Teterboro", tier: "1" },
      { n: "Saskia Borchert", r: "Account Director · NetJets Europe", c: "Lisbon", tier: "2" },
      { n: "Yusuf Khan", r: "Family Office Aviation Lead", c: "Riyadh", tier: "1" },
      { n: "Tomás Ferreira", r: "Director of Maintenance · Embraer", c: "São Paulo", tier: "2" },
    ],
    introContext: "Mutual context: 2 active pre-owned mandates above $40M.",
    contentPrompts: [
      { type: "LinkedIn", t: "Why pre-owned Globals just hit their first sub-list closing" },
      { type: "Reel", t: "Walkthrough: G700 first owner-resale" },
      { type: "Carousel", t: "5 things a senior broker prices before sticker" },
      { type: "Short", t: "Why UHNW are rotating back to whole-aircraft" },
    ],
    studioActions,
    trackName: "Private Aviation",
    trackModules: 31,
    trackProgress: 9,
    modules: [
      { n: "01", t: "How aircraft brokers actually price an asset", dur: "18 min", state: "done" },
      { n: "02", t: "Charter vs fractional vs whole-aircraft: the real math", dur: "22 min", state: "done" },
      { n: "03", t: "Pre-owned market dynamics — long-range segment", dur: "20 min", state: "current" },
      { n: "04", t: "Working with Part 135 operators as a broker", dur: "26 min", state: "locked" },
      { n: "05", t: "Owner psychology: utilization, ego, taxation", dur: "28 min", state: "locked" },
      { n: "06", t: "Building a buyer mandate above $50M", dur: "30 min", state: "locked" },
    ],
    tutorBlurb:
      "Role-play a buyer call for a Global 7500 mandate — AURUM plays a skeptical principal weighing whole vs program.",
    terms: { client: "Principal", asset: "Aircraft", market: "Pre-owned market" },
  },

  cars: {
    id: "cars",
    label: "Cars",
    shortLabel: "Car",
    modeLabel: "Car Mode",
    icon: Car,
    tagline: "Hypercars · collectors · auctions · investment-grade",
    ambientImage: carImg,
    mentorPersona: "AURUM · Collector Counsel",
    mentorSpecialty: "Hypercars, collector auctions, dealer relationships, allocation politics",
    mentorOpener:
      "Good morning, Alexander. RM Sotheby's evening sale ran hot last night. Before we plan today — how did your call with the Pagani allocation contact land?",
    mentorPrompts: [
      "Plan my Monterey Car Week",
      "Review my collector LinkedIn positioning",
      "Draft outreach to a hypercar allocation contact",
      "Coach me through a private-treaty negotiation",
    ],
    greetingSubtitle: "The collector market is moving — and so are you.",
    phaseLabel: "Phase 02 · Hypercar allocation immersion",
    dailyObjectives: [
      "Track 5 auction lots above $1M",
      "Comment on 3 collector posts",
      "Publish a market insight on hypercar allocations",
      "Academy: How allocations actually get awarded",
      "Outreach to 2 OEM allocation contacts",
    ],
    marketTrends: ["911 GT3 RS +18% trail", "RM Sotheby's sell-through 92%", "EV hypercars softening"],
    upcoming: [
      ["Oct 19", "RM Sotheby's London Sale"],
      ["Nov 06", "Mastermind: Allocation Politics"],
      ["Nov 14", "1:1 with Lorenzo P. (Pagani)"],
    ],
    aiRecommendation:
      "Reach Pagani's client relations before the London sale — your collection narrative fits their next Utopia allocation cycle.",
    intelFeed: [
      { tag: "MARKET", title: "Porsche 911 GT3 RS 992 trail-pricing up 18% over 90 days", note: "Limited-allocation cars outperforming as broader market normalizes.", time: "20m", region: "Stuttgart" },
      { tag: "DEAL", title: "Ferrari F40 'Classiche' sells at $3.6M — RM Sotheby's evening", note: "Above estimate. Re-establishes F40 ceiling after 18 months of softness.", time: "55m", region: "Monterey" },
      { tag: "PEOPLE", title: "Lorenzo Pagani opens new Modena atelier — invitation-only previews", note: "Next Utopia allocation cycle informally underway. Window opens for new clients.", time: "2h", region: "Modena" },
      { tag: "EVENT", title: "RM Sotheby's London Sale lot list released — 7 above $2M", note: "11 collectors from your network attending. Strategic week of intros.", time: "5h", region: "London" },
      { tag: "CULTURE", title: "Collector preference rotating from EV hypercars back to ICE icons", note: "Authority opportunity: publish on the EV hypercar correction.", time: "7h", region: "Global" },
      { tag: "REGULATORY", title: "EU classic-car import duty exemptions clarified for 25y+ vehicles", note: "Clarifies pricing for US-sourced air-cooled 911s into EU.", time: "1d", region: "Brussels" },
    ],
    circles: [
      { name: "Hypercar Allocation Insiders", members: 22, tier: "TIER-1", note: "Pagani, Bugatti, Koenigsegg client contacts" },
      { name: "Auction Floor Operators", members: 38, tier: "TIER-2", note: "RM, Gooding, Bonhams reps and consignors" },
      { name: "Authority Builders", members: 118, tier: "OPEN", note: "Content, personal brand, positioning" },
      { name: "Monterey Pre-Week", members: 71, tier: "SEASONAL", note: "Active discussion · 22 today" },
    ],
    people: [
      { n: "Lorenzo Piaggi", r: "Client Relations · Pagani", c: "Modena", tier: "1" },
      { n: "Cassandra Vale", r: "Specialist · RM Sotheby's", c: "London", tier: "1" },
      { n: "Marcus Whitlock", r: "Founder · Whitlock Collection", c: "Greenwich", tier: "1" },
      { n: "Andrea Conti", r: "Director · Ferrari Special Projects", c: "Maranello", tier: "1" },
      { n: "Kenji Hara", r: "Specialist Dealer · Hara Auto", c: "Tokyo", tier: "2" },
      { n: "Olivia Dunne", r: "Hagerty Insider", c: "New York", tier: "2" },
    ],
    introContext: "Mutual context: 2 active allocations in your sector.",
    contentPrompts: [
      { type: "LinkedIn", t: "Why limited-allocation cars are outperforming the broader market" },
      { type: "Reel", t: "60s walkaround: $3.6M F40 'Classiche'" },
      { type: "Carousel", t: "5 questions an OEM allocation team is silently asking you" },
      { type: "Short", t: "What the EV hypercar correction signals for ICE icons" },
    ],
    studioActions,
    trackName: "Exotic Automotive",
    trackModules: 26,
    trackProgress: 7,
    modules: [
      { n: "01", t: "How allocations actually get awarded", dur: "18 min", state: "done" },
      { n: "02", t: "Reading an auction lot like a senior specialist", dur: "22 min", state: "done" },
      { n: "03", t: "Building a collector narrative that earns allocations", dur: "20 min", state: "current" },
      { n: "04", t: "Private-treaty deals vs public auction", dur: "26 min", state: "locked" },
      { n: "05", t: "Working with OEM client-relations as a broker", dur: "28 min", state: "locked" },
      { n: "06", t: "Investment-grade portfolio construction", dur: "30 min", state: "locked" },
    ],
    tutorBlurb:
      "Role-play building your collector narrative for a Pagani Utopia allocation — AURUM plays Lorenzo's client-relations lead.",
    terms: { client: "Collector", asset: "Car", market: "Collector market" },
  },
};

export const INDUSTRY_LIST: IndustryConfig[] = [
  INDUSTRIES.yachts,
  INDUSTRIES.villas,
  INDUSTRIES.jets,
  INDUSTRIES.cars,
];
